### ISSUE TITLE
[Web v1.1.0] default API_ENDPOINT value

### ISSUE THREAD

**Issue by zaarheed** [ionicfirebaseapp/Readymade-grocery-app#13]
Environment variable `API_ENDPOINT` should be `localhost`, not your demo server!

**Comment by adityakoushik11** [comment]
When we publish the application, we want people to check the functionality that's why we give the demo server link, when a client purchases the product and downloads the source code he has tot follow the setup instructions and can change the server url accordingly.

**Comment by pietechsolution** [comment]
We understand and each one has there own way and things as you are programmer so you think that way but our product used by 70% user who not a developer so they preferred to run at least default angular and later once run API and replace.  It's not bug or issue.

**Comment by zaarheed** [comment]
correct its not a bug or issue its a recommendation.

every time you release your updates all your existing customers will get conflicts because their local file will have `localhost` and the update file will have your demo server
