### ISSUE TITLE
[Web v1.1.0] Login button doesn't work

### ISSUE THREAD

**Issue by zaarheed** [ionicfirebaseapp/Readymade-grocery-app#14]
The code for the Login button is:

```
 <button type="submit" class="btn btn-warning sign-btn" [disabled]="loginForm.invalid">
    Log in
</button>
```

Doesn't even include `(click)=""`

**Comment by adityakoushik11** [comment]
The button type is **submit**, the button is inside a form which has **ngSubmit** event binded to it, there is no need to bid click event to the login button.

**Comment by zaarheed** [comment]
login button still doesnt work
