### ISSUE TITLE
[API v1.1.0] provide .env.example file

### ISSUE THREAD

**Issue by zaarheed** [ionicfirebaseapp/Readymade-grocery-app#2]
You should provide a `.env.example` file in the source code so it is easy to reset/update keys. After updating from v1.0.0 to v1.1.0 it is very cumbersome to update all the keys. Same for any servers i deploy to.

**Comment by pietechsolution** [comment]
Now from version 1.1.0 all move into ENV file and in future, we remove from this and plan to go NODE_ENV as well. Even if you want in 1.1.0 you can run all as ENV variable.
