### ISSUE TITLE
[CMS v1.1.0] Sidebar disappears when resizing screen

### ISSUE THREAD

**Issue by zaarheed** [ionicfirebaseapp/Readymade-grocery-app#9]
1. Login to CMS dashboard using Chrome
2. Resize window until sidebar dissapears
3. Resize window back to normal width
4. Sidebar doesn't reappear

**Comment by pietechsolution** [comment]
In general, did you have any use cases like this?  Directly open on mobile it's working and anyway dashboard entire can't be 100% responsive.

**Comment by zaarheed** [comment]
@PietechSolution yes. when the grocery store user opens the browser it doesnt always open maximised
